sylius_twig_hooks:
    hooks:
        'sylius_admin.taxon.update.content.sections.form.translations':
            setono_sylius_redirect_admin_redirect:
                template: '@SetonoSyliusRedirectPlugin/admin/Taxon/add_automatic_redirect.html.twig'
                priority: 50
