setono_sylius_redirect_admin_redirect:
    resource: |
        alias: setono_sylius_redirect.redirect
        section: admin
        permission: true
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: setono_sylius_redirect_admin_redirect
        vars:
            all:
                subheader: setono_sylius_redirect.ui.manage_redirects
                templates:
                    form: "@SetonoSyliusRedirectPlugin/admin/redirect/_form.html.twig"
            index:
                icon: 'chart bar'
    type: sylius.resource
