setono_sylius_redirect_admin_redirect:
    resource: |
        alias: setono_sylius_redirect.redirect
        section: admin
        permission: true
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: update
        grid: setono_sylius_redirect_admin_redirect
    type: sylius.resource
