sylius_grid:
    grids:
        setono_sylius_redirect_admin_redirect:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_redirect.model.redirect.class%"
            fields:
                source:
                    type: string
                    label: setono_sylius_redirect.ui.source
                destination:
                    type: string
                    label: setono_sylius_redirect.ui.destination
                permanent:
                    type: twig
                    label: setono_sylius_redirect.ui.permanent
                    options:
                        template: "@SyliusUi/grid/field/yes_no.html.twig"
                enabled:
                    type: twig
                    label: setono_sylius_redirect.ui.enabled
                    options:
                        template: "@SyliusUi/grid/field/yes_no.html.twig"
                count:
                    type: string
                    label: setono_sylius_redirect.ui.count
                lastAccessed:
                    type: datetime
                    label: setono_sylius_redirect.ui.last_accessed
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    form_options:
                        type: contains
                    options:
                        fields: [source, destination]
                enabled:
                    type: boolean
                    label: setono_sylius_redirect.ui.enabled
                permanent:
                    type: boolean
                    label: setono_sylius_redirect.ui.permanent
                only404:
                    type: boolean
                    label: setono_sylius_redirect.form.redirect.only_404
                channel:
                    type: entity
                    label: setono_sylius_redirect.ui.channels
                    form_options:
                        class: "%sylius.model.channel.class%"
                    options:
                        fields: [channels.id]
            actions:
                main:
                    create:
                        type: create
                item:
                    show:
                        type: show
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
