imports:
- { resource: "@SetonoSyliusRedirectPlugin/config/grids.yaml" }
- { resource: "@SetonoSyliusRedirectPlugin/config/twig_hooks/product.yaml" }
- { resource: "@SetonoSyliusRedirectPlugin/config/twig_hooks/redirect.yaml" }
- { resource: "@SetonoSyliusRedirectPlugin/config/twig_hooks/taxon.yaml" }
