name: "build"

on:
    push: ~
    pull_request: ~
    workflow_dispatch: ~

jobs:
    backwards-compatibility:
        runs-on: "ubuntu-latest"
        if: "github.event_name == 'pull_request'"
        steps:
            -   uses: "setono/sylius-plugin/backwards-compatibility@v2"

    coding-standards:
        runs-on: "ubuntu-latest"
        steps:
            -   uses: "setono/sylius-plugin/coding-standards@v2"

    dependency-analysis:
        runs-on: "ubuntu-latest"
        strategy:
            fail-fast: false
            matrix:
                php-version: ["8.2", "8.3", "8.4"]
                dependencies: ["lowest", "highest"]
                symfony: ["~6.4.0", "~7.4.0"]
        steps:
            -   uses: "setono/sylius-plugin/dependency-analysis@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    dependencies: "${{ matrix.dependencies }}"
                    symfony: "${{ matrix.symfony }}"

    static-code-analysis:
        runs-on: "ubuntu-latest"
        strategy:
            fail-fast: false
            matrix:
                php-version: ["8.2", "8.3", "8.4"]
                dependencies: ["lowest", "highest"]
                symfony: ["~6.4.0", "~7.4.0"]
        steps:
            -   uses: "setono/sylius-plugin/static-code-analysis@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    dependencies: "${{ matrix.dependencies }}"
                    symfony: "${{ matrix.symfony }}"

    unit-tests:
        runs-on: "ubuntu-latest"
        strategy:
            fail-fast: false
            matrix:
                php-version: ["8.2", "8.3", "8.4"]
                dependencies: ["lowest", "highest"]
                symfony: ["~6.4.0", "~7.4.0"]
        steps:
            -   uses: "setono/sylius-plugin/unit-tests@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    dependencies: "${{ matrix.dependencies }}"
                    symfony: "${{ matrix.symfony }}"

    integration-tests:
        runs-on: "ubuntu-latest"
        strategy:
            fail-fast: false
            matrix:
                php-version: ["8.2", "8.3", "8.4"]
                dependencies: ["highest"]
                symfony: ["~6.4.0", "~7.4.0"]
        env:
            DATABASE_URL: "mysql://root:root@127.0.0.1/sylius?serverVersion=8.0"
        steps:
            -   uses: "setono/sylius-plugin/integration-tests@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    dependencies: "${{ matrix.dependencies }}"
                    symfony: "${{ matrix.symfony }}"

            -   shell: "bash"
                run: "vendor/bin/phpunit --testsuite functional"

    code-coverage:
        runs-on: "ubuntu-latest"
        steps:
            -   uses: "setono/sylius-plugin/code-coverage@v2"
                with:
                    codecov-token: "${{ secrets.CODECOV_TOKEN }}"
