name: "build"

on:
    push: ~
    pull_request: ~
    workflow_dispatch: ~

jobs:
    backwards-compatibility:
        runs-on: "ubuntu-latest"
        if: "github.event_name == 'pull_request'"
        steps:
            -   uses: "setono/sylius-plugin/backwards-compatibility@v2"

    coding-standards:
        runs-on: "ubuntu-latest"
        steps:
            -   uses: "setono/sylius-plugin/coding-standards@v2"

    dependency-analysis:
        runs-on: "ubuntu-latest"
        strategy:
            fail-fast: false
            matrix:
                php-version: ["8.2", "8.3", "8.4"]
                dependencies: ["lowest", "highest"]
                symfony: ["~6.4.0", "~7.4.0"]
        steps:
            -   uses: "setono/sylius-plugin/dependency-analysis@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    dependencies: "${{ matrix.dependencies }}"
                    symfony: "${{ matrix.symfony }}"

    static-code-analysis:
        runs-on: "ubuntu-latest"
        strategy:
            fail-fast: false
            matrix:
                php-version: ["8.2", "8.3", "8.4"]
                dependencies: ["lowest", "highest"]
                symfony: ["~6.4.0", "~7.4.0"]
        steps:
            -   uses: "setono/sylius-plugin/static-code-analysis@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    dependencies: "${{ matrix.dependencies }}"
                    symfony: "${{ matrix.symfony }}"

    unit-tests:
        runs-on: "ubuntu-latest"
        strategy:
            fail-fast: false
            matrix:
                php-version: ["8.2", "8.3", "8.4"]
                dependencies: ["lowest", "highest"]
                symfony: ["~6.4.0", "~7.4.0"]
        env:
            DATABASE_URL: "mysql://root:root@127.0.0.1/setono_sylius_redirect_plugin_test?serverVersion=8.0"
        steps:
            -   shell: "bash"
                run: "sudo /etc/init.d/mysql start"

            -   uses: "actions/checkout@v6"

            -   uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    extensions: "intl, mbstring, pdo_mysql"
                    coverage: "none"
                    tools: "flex"

            -   uses: "ramsey/composer-install@v4"
                env:
                    SYMFONY_REQUIRE: "${{ matrix.symfony }}"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"

            -   shell: "bash"
                run: "vendor/bin/phpunit"

    integration-tests:
        runs-on: "ubuntu-latest"
        strategy:
            fail-fast: false
            matrix:
                php-version: ["8.2", "8.3", "8.4"]
                dependencies: ["highest"]
                symfony: ["~6.4.0", "~7.4.0"]
        steps:
            -   uses: "setono/sylius-plugin/integration-tests@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    dependencies: "${{ matrix.dependencies }}"
                    symfony: "${{ matrix.symfony }}"

    code-coverage:
        runs-on: "ubuntu-latest"
        env:
            DATABASE_URL: "mysql://root:root@127.0.0.1/setono_sylius_redirect_plugin_test?serverVersion=8.0"
        steps:
            -   shell: "bash"
                run: "sudo /etc/init.d/mysql start"

            -   uses: "actions/checkout@v6"

            -   uses: "shivammathur/setup-php@v2"
                with:
                    extensions: "intl, mbstring, pdo_mysql"
                    coverage: "pcov"

            -   uses: "ramsey/composer-install@v4"

            -   shell: "bash"
                run: "vendor/bin/phpunit --coverage-clover=.build/logs/clover.xml"

            -   uses: "codecov/codecov-action@v5"
                with:
                    token: "${{ secrets.CODECOV_TOKEN }}"
